/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelecoesRouteImport } from './routes/selecoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MataMataRouteImport } from './routes/mata-mata'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as CriarBolaoRouteImport } from './routes/criar-bolao'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelecoesIdRouteImport } from './routes/selecoes.$id'
import { Route as PartidasIdRouteImport } from './routes/partidas.$id'
import { Route as MeusPalpitesSlugRouteImport } from './routes/meus-palpites.$slug'
import { Route as BolaoSlugRouteImport } from './routes/bolao.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as BolaoSlugRankingRouteImport } from './routes/bolao.$slug.ranking'
import { Route as AuthV1SplatRouteImport } from './routes/auth/v1/$'
import { Route as AuthenticatedAppWhatsappRouteImport } from './routes/_authenticated/app.whatsapp'
import { Route as AuthenticatedAppTorcedoresRouteImport } from './routes/_authenticated/app.torcedores'
import { Route as AuthenticatedAppSegurancaRouteImport } from './routes/_authenticated/app.seguranca'
import { Route as AuthenticatedAppPixRouteImport } from './routes/_authenticated/app.pix'
import { Route as AuthenticatedAppPalpitesRouteImport } from './routes/_authenticated/app.palpites'
import { Route as AuthenticatedAppGestoresRouteImport } from './routes/_authenticated/app.gestores'
import { Route as AuthenticatedAppGanhadoresRouteImport } from './routes/_authenticated/app.ganhadores'
import { Route as AuthenticatedAppContatosRouteImport } from './routes/_authenticated/app.contatos'
import { Route as AuthenticatedAppBolaoRouteImport } from './routes/_authenticated/app.bolao'
import { Route as AuthenticatedAppAuditoriaRouteImport } from './routes/_authenticated/app.auditoria'
import { Route as ApiPublicHooksSyncFootballRouteImport } from './routes/api/public/hooks/sync-football'
import { Route as ApiPublicHooksDispatchPushRouteImport } from './routes/api/public/hooks/dispatch-push'
import { Route as ApiPublicHooksDispatchNotificationsRouteImport } from './routes/api/public/hooks/dispatch-notifications'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesRoute = SelecoesRouteImport.update({
  id: '/selecoes',
  path: '/selecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MataMataRoute = MataMataRouteImport.update({
  id: '/mata-mata',
  path: '/mata-mata',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarBolaoRoute = CriarBolaoRouteImport.update({
  id: '/criar-bolao',
  path: '/criar-bolao',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesIdRoute = SelecoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SelecoesRoute,
} as any)
const PartidasIdRoute = PartidasIdRouteImport.update({
  id: '/partidas/$id',
  path: '/partidas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPalpitesSlugRoute = MeusPalpitesSlugRouteImport.update({
  id: '/meus-palpites/$slug',
  path: '/meus-palpites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BolaoSlugRoute = BolaoSlugRouteImport.update({
  id: '/bolao/$slug',
  path: '/bolao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const BolaoSlugRankingRoute = BolaoSlugRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => BolaoSlugRoute,
} as any)
const AuthV1SplatRoute = AuthV1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppWhatsappRoute =
  AuthenticatedAppWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTorcedoresRoute =
  AuthenticatedAppTorcedoresRouteImport.update({
    id: '/torcedores',
    path: '/torcedores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSegurancaRoute =
  AuthenticatedAppSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPixRoute = AuthenticatedAppPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPalpitesRoute =
  AuthenticatedAppPalpitesRouteImport.update({
    id: '/palpites',
    path: '/palpites',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGestoresRoute =
  AuthenticatedAppGestoresRouteImport.update({
    id: '/gestores',
    path: '/gestores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGanhadoresRoute =
  AuthenticatedAppGanhadoresRouteImport.update({
    id: '/ganhadores',
    path: '/ganhadores',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContatosRoute =
  AuthenticatedAppContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBolaoRoute = AuthenticatedAppBolaoRouteImport.update({
  id: '/bolao',
  path: '/bolao',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditoriaRoute =
  AuthenticatedAppAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksSyncFootballRoute =
  ApiPublicHooksSyncFootballRouteImport.update({
    id: '/api/public/hooks/sync-football',
    path: '/api/public/hooks/sync-football',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchPushRoute =
  ApiPublicHooksDispatchPushRouteImport.update({
    id: '/api/public/hooks/dispatch-push',
    path: '/api/public/hooks/dispatch-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchNotificationsRoute =
  ApiPublicHooksDispatchNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-notifications',
    path: '/api/public/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/criar-bolao': typeof CriarBolaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selecoes': typeof SelecoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/bolao/$slug': typeof BolaoSlugRouteWithChildren
  '/meus-palpites/$slug': typeof MeusPalpitesSlugRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/bolao': typeof AuthenticatedAppBolaoRoute
  '/app/contatos': typeof AuthenticatedAppContatosRoute
  '/app/ganhadores': typeof AuthenticatedAppGanhadoresRoute
  '/app/gestores': typeof AuthenticatedAppGestoresRoute
  '/app/palpites': typeof AuthenticatedAppPalpitesRoute
  '/app/pix': typeof AuthenticatedAppPixRoute
  '/app/seguranca': typeof AuthenticatedAppSegurancaRoute
  '/app/torcedores': typeof AuthenticatedAppTorcedoresRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/auth/v1/$': typeof AuthV1SplatRoute
  '/bolao/$slug/ranking': typeof BolaoSlugRankingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/criar-bolao': typeof CriarBolaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selecoes': typeof SelecoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/bolao/$slug': typeof BolaoSlugRouteWithChildren
  '/meus-palpites/$slug': typeof MeusPalpitesSlugRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/bolao': typeof AuthenticatedAppBolaoRoute
  '/app/contatos': typeof AuthenticatedAppContatosRoute
  '/app/ganhadores': typeof AuthenticatedAppGanhadoresRoute
  '/app/gestores': typeof AuthenticatedAppGestoresRoute
  '/app/palpites': typeof AuthenticatedAppPalpitesRoute
  '/app/pix': typeof AuthenticatedAppPixRoute
  '/app/seguranca': typeof AuthenticatedAppSegurancaRoute
  '/app/torcedores': typeof AuthenticatedAppTorcedoresRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/auth/v1/$': typeof AuthV1SplatRoute
  '/bolao/$slug/ranking': typeof BolaoSlugRankingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/criar-bolao': typeof CriarBolaoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/grupos': typeof GruposRoute
  '/mata-mata': typeof MataMataRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selecoes': typeof SelecoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/bolao/$slug': typeof BolaoSlugRouteWithChildren
  '/meus-palpites/$slug': typeof MeusPalpitesSlugRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/_authenticated/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/_authenticated/app/bolao': typeof AuthenticatedAppBolaoRoute
  '/_authenticated/app/contatos': typeof AuthenticatedAppContatosRoute
  '/_authenticated/app/ganhadores': typeof AuthenticatedAppGanhadoresRoute
  '/_authenticated/app/gestores': typeof AuthenticatedAppGestoresRoute
  '/_authenticated/app/palpites': typeof AuthenticatedAppPalpitesRoute
  '/_authenticated/app/pix': typeof AuthenticatedAppPixRoute
  '/_authenticated/app/seguranca': typeof AuthenticatedAppSegurancaRoute
  '/_authenticated/app/torcedores': typeof AuthenticatedAppTorcedoresRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/auth/v1/$': typeof AuthV1SplatRoute
  '/bolao/$slug/ranking': typeof BolaoSlugRankingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/calendario'
    | '/criar-bolao'
    | '/estatisticas'
    | '/grupos'
    | '/mata-mata'
    | '/planos'
    | '/reset-password'
    | '/selecoes'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/bolao/$slug'
    | '/meus-palpites/$slug'
    | '/partidas/$id'
    | '/selecoes/$id'
    | '/app/auditoria'
    | '/app/bolao'
    | '/app/contatos'
    | '/app/ganhadores'
    | '/app/gestores'
    | '/app/palpites'
    | '/app/pix'
    | '/app/seguranca'
    | '/app/torcedores'
    | '/app/whatsapp'
    | '/auth/v1/$'
    | '/bolao/$slug/ranking'
    | '/app/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/sync-football'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/calendario'
    | '/criar-bolao'
    | '/estatisticas'
    | '/grupos'
    | '/mata-mata'
    | '/planos'
    | '/reset-password'
    | '/selecoes'
    | '/sitemap.xml'
    | '/admin'
    | '/onboarding'
    | '/bolao/$slug'
    | '/meus-palpites/$slug'
    | '/partidas/$id'
    | '/selecoes/$id'
    | '/app/auditoria'
    | '/app/bolao'
    | '/app/contatos'
    | '/app/ganhadores'
    | '/app/gestores'
    | '/app/palpites'
    | '/app/pix'
    | '/app/seguranca'
    | '/app/torcedores'
    | '/app/whatsapp'
    | '/auth/v1/$'
    | '/bolao/$slug/ranking'
    | '/app'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/sync-football'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/auth'
    | '/calendario'
    | '/criar-bolao'
    | '/estatisticas'
    | '/grupos'
    | '/mata-mata'
    | '/planos'
    | '/reset-password'
    | '/selecoes'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/bolao/$slug'
    | '/meus-palpites/$slug'
    | '/partidas/$id'
    | '/selecoes/$id'
    | '/_authenticated/app/auditoria'
    | '/_authenticated/app/bolao'
    | '/_authenticated/app/contatos'
    | '/_authenticated/app/ganhadores'
    | '/_authenticated/app/gestores'
    | '/_authenticated/app/palpites'
    | '/_authenticated/app/pix'
    | '/_authenticated/app/seguranca'
    | '/_authenticated/app/torcedores'
    | '/_authenticated/app/whatsapp'
    | '/auth/v1/$'
    | '/bolao/$slug/ranking'
    | '/_authenticated/app/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/sync-football'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  CriarBolaoRoute: typeof CriarBolaoRoute
  EstatisticasRoute: typeof EstatisticasRoute
  GruposRoute: typeof GruposRoute
  MataMataRoute: typeof MataMataRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelecoesRoute: typeof SelecoesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BolaoSlugRoute: typeof BolaoSlugRouteWithChildren
  MeusPalpitesSlugRoute: typeof MeusPalpitesSlugRoute
  PartidasIdRoute: typeof PartidasIdRoute
  ApiPublicHooksDispatchNotificationsRoute: typeof ApiPublicHooksDispatchNotificationsRoute
  ApiPublicHooksDispatchPushRoute: typeof ApiPublicHooksDispatchPushRoute
  ApiPublicHooksSyncFootballRoute: typeof ApiPublicHooksSyncFootballRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes': {
      id: '/selecoes'
      path: '/selecoes'
      fullPath: '/selecoes'
      preLoaderRoute: typeof SelecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mata-mata': {
      id: '/mata-mata'
      path: '/mata-mata'
      fullPath: '/mata-mata'
      preLoaderRoute: typeof MataMataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-bolao': {
      id: '/criar-bolao'
      path: '/criar-bolao'
      fullPath: '/criar-bolao'
      preLoaderRoute: typeof CriarBolaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes/$id': {
      id: '/selecoes/$id'
      path: '/$id'
      fullPath: '/selecoes/$id'
      preLoaderRoute: typeof SelecoesIdRouteImport
      parentRoute: typeof SelecoesRoute
    }
    '/partidas/$id': {
      id: '/partidas/$id'
      path: '/partidas/$id'
      fullPath: '/partidas/$id'
      preLoaderRoute: typeof PartidasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-palpites/$slug': {
      id: '/meus-palpites/$slug'
      path: '/meus-palpites/$slug'
      fullPath: '/meus-palpites/$slug'
      preLoaderRoute: typeof MeusPalpitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolao/$slug': {
      id: '/bolao/$slug'
      path: '/bolao/$slug'
      fullPath: '/bolao/$slug'
      preLoaderRoute: typeof BolaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/bolao/$slug/ranking': {
      id: '/bolao/$slug/ranking'
      path: '/ranking'
      fullPath: '/bolao/$slug/ranking'
      preLoaderRoute: typeof BolaoSlugRankingRouteImport
      parentRoute: typeof BolaoSlugRoute
    }
    '/auth/v1/$': {
      id: '/auth/v1/$'
      path: '/v1/$'
      fullPath: '/auth/v1/$'
      preLoaderRoute: typeof AuthV1SplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/torcedores': {
      id: '/_authenticated/app/torcedores'
      path: '/torcedores'
      fullPath: '/app/torcedores'
      preLoaderRoute: typeof AuthenticatedAppTorcedoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seguranca': {
      id: '/_authenticated/app/seguranca'
      path: '/seguranca'
      fullPath: '/app/seguranca'
      preLoaderRoute: typeof AuthenticatedAppSegurancaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pix': {
      id: '/_authenticated/app/pix'
      path: '/pix'
      fullPath: '/app/pix'
      preLoaderRoute: typeof AuthenticatedAppPixRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/palpites': {
      id: '/_authenticated/app/palpites'
      path: '/palpites'
      fullPath: '/app/palpites'
      preLoaderRoute: typeof AuthenticatedAppPalpitesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gestores': {
      id: '/_authenticated/app/gestores'
      path: '/gestores'
      fullPath: '/app/gestores'
      preLoaderRoute: typeof AuthenticatedAppGestoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ganhadores': {
      id: '/_authenticated/app/ganhadores'
      path: '/ganhadores'
      fullPath: '/app/ganhadores'
      preLoaderRoute: typeof AuthenticatedAppGanhadoresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contatos': {
      id: '/_authenticated/app/contatos'
      path: '/contatos'
      fullPath: '/app/contatos'
      preLoaderRoute: typeof AuthenticatedAppContatosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bolao': {
      id: '/_authenticated/app/bolao'
      path: '/bolao'
      fullPath: '/app/bolao'
      preLoaderRoute: typeof AuthenticatedAppBolaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/auditoria': {
      id: '/_authenticated/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/sync-football': {
      id: '/api/public/hooks/sync-football'
      path: '/api/public/hooks/sync-football'
      fullPath: '/api/public/hooks/sync-football'
      preLoaderRoute: typeof ApiPublicHooksSyncFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-push': {
      id: '/api/public/hooks/dispatch-push'
      path: '/api/public/hooks/dispatch-push'
      fullPath: '/api/public/hooks/dispatch-push'
      preLoaderRoute: typeof ApiPublicHooksDispatchPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-notifications': {
      id: '/api/public/hooks/dispatch-notifications'
      path: '/api/public/hooks/dispatch-notifications'
      fullPath: '/api/public/hooks/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAuditoriaRoute: typeof AuthenticatedAppAuditoriaRoute
  AuthenticatedAppBolaoRoute: typeof AuthenticatedAppBolaoRoute
  AuthenticatedAppContatosRoute: typeof AuthenticatedAppContatosRoute
  AuthenticatedAppGanhadoresRoute: typeof AuthenticatedAppGanhadoresRoute
  AuthenticatedAppGestoresRoute: typeof AuthenticatedAppGestoresRoute
  AuthenticatedAppPalpitesRoute: typeof AuthenticatedAppPalpitesRoute
  AuthenticatedAppPixRoute: typeof AuthenticatedAppPixRoute
  AuthenticatedAppSegurancaRoute: typeof AuthenticatedAppSegurancaRoute
  AuthenticatedAppTorcedoresRoute: typeof AuthenticatedAppTorcedoresRoute
  AuthenticatedAppWhatsappRoute: typeof AuthenticatedAppWhatsappRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAuditoriaRoute: AuthenticatedAppAuditoriaRoute,
  AuthenticatedAppBolaoRoute: AuthenticatedAppBolaoRoute,
  AuthenticatedAppContatosRoute: AuthenticatedAppContatosRoute,
  AuthenticatedAppGanhadoresRoute: AuthenticatedAppGanhadoresRoute,
  AuthenticatedAppGestoresRoute: AuthenticatedAppGestoresRoute,
  AuthenticatedAppPalpitesRoute: AuthenticatedAppPalpitesRoute,
  AuthenticatedAppPixRoute: AuthenticatedAppPixRoute,
  AuthenticatedAppSegurancaRoute: AuthenticatedAppSegurancaRoute,
  AuthenticatedAppTorcedoresRoute: AuthenticatedAppTorcedoresRoute,
  AuthenticatedAppWhatsappRoute: AuthenticatedAppWhatsappRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthV1SplatRoute: typeof AuthV1SplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthV1SplatRoute: AuthV1SplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SelecoesRouteChildren {
  SelecoesIdRoute: typeof SelecoesIdRoute
}

const SelecoesRouteChildren: SelecoesRouteChildren = {
  SelecoesIdRoute: SelecoesIdRoute,
}

const SelecoesRouteWithChildren = SelecoesRoute._addFileChildren(
  SelecoesRouteChildren,
)

interface BolaoSlugRouteChildren {
  BolaoSlugRankingRoute: typeof BolaoSlugRankingRoute
}

const BolaoSlugRouteChildren: BolaoSlugRouteChildren = {
  BolaoSlugRankingRoute: BolaoSlugRankingRoute,
}

const BolaoSlugRouteWithChildren = BolaoSlugRoute._addFileChildren(
  BolaoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  CriarBolaoRoute: CriarBolaoRoute,
  EstatisticasRoute: EstatisticasRoute,
  GruposRoute: GruposRoute,
  MataMataRoute: MataMataRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelecoesRoute: SelecoesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BolaoSlugRoute: BolaoSlugRouteWithChildren,
  MeusPalpitesSlugRoute: MeusPalpitesSlugRoute,
  PartidasIdRoute: PartidasIdRoute,
  ApiPublicHooksDispatchNotificationsRoute:
    ApiPublicHooksDispatchNotificationsRoute,
  ApiPublicHooksDispatchPushRoute: ApiPublicHooksDispatchPushRoute,
  ApiPublicHooksSyncFootballRoute: ApiPublicHooksSyncFootballRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
